### ISSUE TITLE
Uranium hexafluoride invalid compound name

### ISSUE THREAD

**Issue by sgitkene** [lambdacasserole/avogadrio#21]
I've stumbled across some molecules that don't work. Uranium hexafluoride is apparently an invalid compound name, uranyl nitrate leads to the "backup" molecule.

**Comment by sgitkene** [comment]
https://en.wikipedia.org/wiki/Heme also doesn't work ("backup")
https://en.wikipedia.org/wiki/Porphin is displayed rather weirdly (see screenshot)

**Comment by lambdacasserole** [comment]
Hi there, thank you very much for making me aware of this. Heme and uranyl nitrate don't seem to be rendering properly because for whatever reason the service at `https://cactus.nci.nih.gov/chemical/structure` is giving back vertical pipe characters `|` when converting the compound name to SMILES. For example, uranyl nitrate gives:

```
O(|[U](|O[N+]([O-])=O)(=O)=O)[N+]([O-])=O
```

Adding some code to strip vertical pipe characters results a render for both uranyl nitrate and heme, but both are pretty messed up.

I didn't think `|` appeared in valid SMILES. Any idea what it signifies @sgitkene?

**Comment by lambdacasserole** [comment]
Uranium hexafluoride appears to just be straight up missing from the online chemical database. Might be worth just adding a local database full of these exceptional cases or maybe integrating another lookup service to fall back on. Or both.

**Comment by lambdacasserole** [comment]
Yep, got an idea about how to proceed with this. Gonna add a chain of responsibility against several compound name-SMILES lookup services until one of them gives us back valid SMILES. I've added one that scrapes SMILES from Wikipedia as a last resort, but hasn't been tested enough to merge in. Efforts ongoing.

**Comment by lambdacasserole** [comment]
Alrighty, fix (for most of the issues you described) is live as of #22 merge:

Uranium hexafluoride: https://avogadr.io/?background=000000&foreground=ffffff&compound=uranium%20hexafluoride

Heme B: https://avogadr.io/?background=000000&foreground=ffffff&compound=heme%20b

Uranyl nitrate: https://avogadr.io/?background=000000&foreground=ffffff&compound=uranyl%20nitrate

Porphin is still a bit of a mystery. Seems like something on the rendering side might need a bit of a tweak. I'll pop it in a separate issue.
